// 心情选项
export const MOOD_OPTIONS = [
  { emoji: '☀️', label: '晴天' },
  { emoji: '☕', label: '喝咖啡中' },
  { emoji: '🍲', label: '想吃火锅' },
  { emoji: '😊', label: '开心' },
  { emoji: '😴', label: '困了' },
  { emoji: '🎵', label: '听音乐' },
  { emoji: '📚', label: '阅读中' },
  { emoji: '🏃', label: '运动中' },
  { emoji: '🌙', label: '晚安' },
  { emoji: '✨', label: '美好时刻' },
  { emoji: '🥤', label: '喝奶茶中' },
  { emoji: '🍱', label: '干饭人上线' },
  { emoji: '💻', label: '努力搬砖' },
  { emoji: '🎮', label: '游戏时间' },
  { emoji: '🛌', label: '只想躺平' },
  { emoji: '😌', label: '放松一下' },
  { emoji: '😤', label: '有点小烦' },
  { emoji: '🥳', label: '超级开心' },
  { emoji: '🤔', label: '思考人生' },
  { emoji: '😎', label: '状态在线' },
  { emoji: '🍵', label: '喝茶摸鱼' },
  { emoji: '🚶', label: '出门散步' },
  { emoji: '🎬', label: '追剧进行中' },
  { emoji: '💤', label: '呼呼大睡' },
  { emoji: '❤️', label: '心情超棒' },
  { emoji: '😋', label: '胃口大开' },
  { emoji: '🙄', label: '无语住了' },
  { emoji: '🌟', label: '元气满满' },
  { emoji: '🍃', label: '微风正好' },
  { emoji: '💪', label: '加油奋斗' },
];
