name: Deploy

on:
  push:
    branches:
      - go-migration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: nekiro/ssh-job@v1.1.0
        with:
          # Target machine hostname or ip
          host: ${{ secrets.SERVER_HOST }}
          # Ssh private key used to connect to target machine
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Ssh user
          user: ${{ secrets.SERVER_USER }}
          # Bash commands ran on target machine
          command: |
            cd /home/ubuntu/mahirooyama-blog/
            git pull --rebase
            docker compose up -d --build next-frontend backend-go
